[phases.setup]
nixpkgs = ["php", "composer", "nodejs", "npm"]

[phases.build]
cmds = [
  "composer install",
  "npm install",
  "php artisan optimize",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan migrate --force",
  "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"
